// Command app is a tiny echo server used by examples/interpolation to make
// resolved interpolation visible at runtime: it reports the flags it was
// given, the build-time tag injected via ldflags, and the contents of the
// config file generated by the Alphasfile.
package main

import (
	"flag"
	"fmt"
	"net/http"
	"os"
)

// Tag is overridden at build time via:
//   go build -ldflags "-X main.Tag=<pathhash>" ...
// which the Alphasfile's `build` interpolation sets — proving `build` is
// itself interpolated.
var Tag = "unset"

func main() {
	addr := flag.String("addr", "127.0.0.1:8080", "listen address")
	cache := flag.String("cache", "", "cache service address (cross-service interp)")
	conf := flag.String("conf", "", "generated config file path")
	flag.Parse()

	body, _ := os.ReadFile(*conf)
	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "tag(ldflags)=%s\naddr=%s\ncache=%s\nconf=%s\n",
			Tag, *addr, *cache, *conf)
		// env precedence demo: SOURCE shows whether the global .env, the
		// per-service dotenv, or the env{} block won (env{} overrides).
		fmt.Fprintf(w, "--- env ---\nSOURCE=%s\nGLOBAL_ONLY=%s\nAPI_LABEL=%s\nCACHE_ADDR=%s\n",
			os.Getenv("SOURCE"), os.Getenv("GLOBAL_ONLY"),
			os.Getenv("API_LABEL"), os.Getenv("CACHE_ADDR"))
		fmt.Fprintf(w, "--- conf ---\n%s", body)
	})
	fmt.Printf("app: tag=%s addr=%s cache=%s conf=%s\n", Tag, *addr, *cache, *conf)
	if err := http.ListenAndServe(*addr, mux); err != nil {
		fmt.Fprintln(os.Stderr, "app:", err)
		os.Exit(1)
	}
}
